### 创建数组

In [8]:
import numpy as np

# 创建数组 -> np.array
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1   # array([6. , 7.5, 8. , 0. , 1. ])
arr1.dtype   #dtype('float64')

data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2.shape   #(2,4)  2*4
arr2.ndim  #n-dimensions  2
arr2.dtype  #dtype('int64')

dtype('float64')

### ndarray 数据类型

In [24]:
#np.zeros/ones/empty/arange
np.zeros(10)   #array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
np.zeros((3,4))   # 3*4 ->0
np.ones(10)
np.ones((3,4))

np.empty((2,3))   #2 lists，3 elements (list-list)
np.empty((2,3,4))   #2 outer-list, 3 inner-list, 4 elements  (list-list-list)
# 输出非0值， 初始垃圾值

np.arange(10).dtype  # array-range==range(10)   ->array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) -> dtype('int64')


# 指定数据类型 dtype=np.xxxtype
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)
arr1.dtype  # dtype('float64')
arr2.dtype  # dtype('int32')

#转换dtype ->.astype(np.xxxtype)  ->调用astye会创建一个新的数组
arr = np.array([1,2,3,4,5])
arr.dtype  # dtype('int64')

new_arr = arr.astype(np.float64)
new_arr = arr.astype(np.string_)   # dtype('S21')
new_arr.dtype  #dtype('float64')
# ps: 如果将浮点数转换成整数，则小数部分会被截断

int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)  #float64


dtype('int64')

### 数组、标量之间的运算

In [44]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr * arr  # array([[ 1.,  4.,  9.],[16., 25., 36.]])
arr - arr
1/arr
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### 索引、切片

In [60]:
arr = np.arange(10)   # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[5] # 5
arr[5:8] # array([5, 6, 7])
#赋值
arr[5:8] = 12  #所有的值都赋值为12
arr    # array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])


# 注意：复制不能简单的复制，而应该 arr_slice = arr[5:8].copy()
arr_slice = arr[5:8]   # array([12, 12, 12])
arr_slice[1] = 12345
arr   # array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,    9])

#二维数组， index[a,b]-> a: 横坐标 ；b:纵坐标
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]   # array([7, 8, 9])
arr2d[0][2]  # 3  ->  arr2d[0][2] == arr2d[0,2]

# 多维数组 index[0]表示最外面list里的第一个整体元素（也可能是多维数组）

#二维切片索引
arr2d[:2]    # array([[1, 2, 3],[4, 5, 6]])
arr2d[:2, 1:]  # array([[2, 3],[5, 6]])
arr2d[1, :2]  # array([4, 5])
arr2d[:, :1]  # array([[1],[4],[7]])

array([[1],
       [4],
       [7]])

### 布尔型索引

In [78]:
from numpy.random import randn
# 或者 np.random.randn()

names = np.array(['Bob','joe','will','Bob','will','joe','joe'])
data = randn(7,4) # 形成7*4的数组  (索引？)
data
names == 'Bob'  # array([ True, False, False,  True, False, False, False])
data[names == 'Bob']
data[names == 'Bob', 2:]
data[~(names == 'Bob')]  # '~'->否定; 或者用names != 'Bob'
# 和&，或者｜（不能用and／or）

# 设置值 
data[data < 0] = 0
data
data[names != 'joe'] = 7
data


array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.2529456 , 0.26177586, 0.97832345],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.83740787, 0.35347514],
       [0.61701688, 0.4259511 , 0.        , 0.        ]])

###  花式索引 （利用整数数组进行索引）-> 与索引不同，总是把数据复制到新数组中

In [110]:
arr = np.empty((8, 4))  # 8*4的数组
for i in range(8):
    arr[i] = i
arr[[4,3,0,6]] # 指定特定的顺序
arr[[-3,-5,-7]]

# .reshape((a,b))
arr = np.arange(32).reshape((8,4))  # 形成8*4的数组，由0～31组成
arr[[1,5,7,2],[0,3,1,2]]  # 选取特定行，特定列 -> array([ 4, 23, 29, 10])
arr[[1,5,7,2]] [:,[0,3,1,2]]  # 选取特定行， 列进行换位 -> 矩阵
arr[np.ix_([1,5,7,2],[0,3,1,2])]  # np.ix_函数，结果同上->矩阵

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 数轴转置和轴对换

In [31]:
import numpy as np
# .T
arr = np.arange(15).reshape((3,5))
arr.T

# 求矩阵内积  np.dot
arr = np.random.randn(6,3)
np.dot(arr.T, arr)  # (3,3)型

# transpose() / swapaxes()
arr = np.arange(30).reshape(3, 2, 5)
arr.shape  #(3, 2, 5)

np.transpose(arr, (0, 2, 1))  # 调换arr.shape的顺序 -> (3,5,2), 内部元素也按照这个规律改变（a,b,c）
arr.swapaxes(1,2) # index［1］与index[2]轴调换 ->(3, 5, 2)


array([[[ 0,  5],
        [ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9]],

       [[10, 15],
        [11, 16],
        [12, 17],
        [13, 18],
        [14, 19]],

       [[20, 25],
        [21, 26],
        [22, 27],
        [23, 28],
        [24, 29]]])

### 利用数据进行数据处理

In [ ]:
# eg -> np.meshgrid()生成以某点为中心的指定半径内的分布情况 / np.where(条件，T的值，F的值) 三元表达式
# matplotlib.imshow()
# np.sort()
# np.unique()



### 将数组以二进制格式保存到磁盘

In [ ]:
# np.save/ np.load


